codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        # basic
        target: 70%
        threshold: 0%
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
        # advanced settings
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
