version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.11

jobs:
  deploy:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install dependancies
          command: yarn ci

      - run:
          name: Bundle application using react-script
          command: yarn build

      - aws-s3/sync:
          from: build
          to: 's3://github-issues-app/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths: ./**
