version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8
  cypress: cypress-io/cypress@1.23.0
  codecov: codecov/codecov@1.0.2
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  checkout:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

  setup:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - run:
          name: Install dependancies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

  scan:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: false
          severity-threshold: high

  lint:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - run:
          name: Linting for src code base
          command: yarn lint

  size:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - run:
          name: App size, loading and running time inspection
          command: yarn size

  test:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - run:
          name: App unit test using Jest
          command: yarn test:ci

  codecov:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - codecov/upload:
          file: './coverage/clover.xml'
          token: ${CODECOV_TOKEN}

  e2e:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - run:
          name: App end to end integration test run
          command: yarn ci:cypress-run

  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - run:
          name: Bundle application using react-script
          command: yarn build

  deploy:
    docker:
      - image: circleci/node:12.9.1

    working_directory: ~/repo

    steps:
      - aws-s3/sync:
          from: app-ci-build
          to: 's3://github-issues-app/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

workflows:
  version: 2
  app_workflow:
    jobs:
      - checkout
      - setup
        requires:
          - checkout
      - scan
        requires:
          - checkout
          - setup
      - lint
        requires:
          - checkout
          - setup
      - size
        requires:
          - checkout
          - setup
      - test
        requires:
          - checkout
          - setup
          - scan
          - lint
      - codecov
        requires:
          - checkout
          - setup
          - scan
          - lint
          - size
          - test
      - e2e
        requires:
          - checkout
          - setup
          - scan
          - lint
          - size
          - test
          - codecov
      - build
        requires:
          - checkout
          - setup
          - scan
          - lint
          - size
          - test
          - codecov
          - e2e
      - deploy:
          requires:
            - checkout
            - setup
            - scan
            - lint
            - size
            - test
            - codecov
            - e2e
            - build
          filters:
            branches:
              only: main
            tags:
              only: /^v.*/
