version: 2.1
orbs:
  snyk: snyk/snyk@0.0.8
  cypress: cypress-io/cypress@1.23.0
  codecov: codecov/codecov@1.0.2
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  checkout:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - persist_to_workspace:
          root: .
          paths: .

  setup:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run: ls -l ~/repo

      - run:
          name: Install dependancies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: .
          paths: .

  scan:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run: ls -l ~/repo

      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: false
          severity-threshold: high

      - persist_to_workspace:
          root: .
          paths: .

  lint:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run: ls -l ~/repo

      - run:
          name: Linting for src code base
          command: yarn lint

      - persist_to_workspace:
          root: .
          paths: .

  size:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run: ls -l ~/repo

      - run:
          name: App size, loading and running time inspection
          command: yarn size

      - persist_to_workspace:
          root: .
          paths: .

  test:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run: ls -l ~/repo

      - run:
          name: App unit test using Jest
          command: yarn test:ci

      - persist_to_workspace:
          root: .
          paths: .

  codecov:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run: ls -l ~/repo

      - codecov/upload:
          file: './coverage/clover.xml'
          token: ${CODECOV_TOKEN}

      - persist_to_workspace:
          root: .
          paths: .

  e2e:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run: ls -l ~/repo

      - run:
          name: App end to end integration test run
          command: yarn ci:cypress-run

      - persist_to_workspace:
          root: .
          paths: .

  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run: ls -l ~/repo

      - run:
          name: Bundle application using react-script
          command: yarn build

      - persist_to_workspace:
          root: .
          paths: .

  deploy:
    docker:
      - image: circleci/node:12.9.1

    working_directory: ~/repo

    steps:
      - checkout

      - attach_workspace:
          at: ~/repo

      - run: ls -l ~/repo

      - aws-s3/sync:
          from: build
          to: 's3://github-issues-app/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

      - persist_to_workspace:
          root: .
          paths: .

workflows:
  version: 2
  app_workflow:
    jobs:
      - checkout
      - setup:
          requires:
            - checkout
      - scan:
          requires:
            - setup
      - lint:
          requires:
            - setup
      - size:
          requires:
            - setup
      - test:
          requires:
            - scan
            - lint
      - codecov:
          requires:
            - test
      - e2e:
          requires:
            - codecov
      - build:
          requires:
            - e2e
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
            tags:
              only: /^v.*/
